### ISSUE TITLE
Consider switching away from go.hid to karalabe/hid

### ISSUE THREAD

**Issue by nathanjsweet** [marshallbrekka/go-u2fhost#4]
The [go.hid project](https://github.com/GeertJohan/go.hid) has declared itself deprecated and recommends switching to [this hid project](https://github.com/karalabe/hid). I would be a fan of doing this since it packages up libusb with the project. Not everyone will have libusb installed on their system, so this approach is preferable.

**Comment by marshallbrekka** [comment]
Hey @nathanjsweet, seems like you're 2 steps ahead of me :)

I discovered that on friday as well while looking into the linux support issue (which you beat me too as well).

I also realized that the license I chose is probably not compatible with the current dependencies (another good reason to switch to that project).

If you want to take a stab at it go for it, otherwise I'll probably get to it some point this week.

**Comment by marshallbrekka** [comment]
closed by https://github.com/marshallbrekka/go-u2fhost/pull/5/files
